/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import io.ktor.server.engine.*
import io.ktor.server.netty.*
import io.ktor.server.application.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import org.example.routes.playlistRoutes
import org.example.routes.friendsRoutes

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    embeddedServer(Netty, port = 8080) {
        routing {
            get("/") {
                call.respondText("Hello from Ktor2222!")
            }
            playlistRoutes()
            friendsRoutes()
        }
    }.start(wait = true)
}
